<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Associado extends \Application\Entity\Associado implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'idAssociado', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'noAssociado', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'nuCpf', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'nuRg', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dtNascimento', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dsEndereco', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dsCidade', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dsProfissao', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dsEnderecoCom', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'nuTelefoneCom', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'nuTelefone', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dsEmail', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'stAutorizaEmail', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'nuTitulo', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dtCadastro', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'idUsuario', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'usuario', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'stAlteraSenha');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'idAssociado', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'noAssociado', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'nuCpf', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'nuRg', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dtNascimento', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dsEndereco', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dsCidade', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dsProfissao', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dsEnderecoCom', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'nuTelefoneCom', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'nuTelefone', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dsEmail', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'stAutorizaEmail', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'nuTitulo', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'dtCadastro', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'idUsuario', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'usuario', '' . "\0" . 'Application\\Entity\\Associado' . "\0" . 'stAlteraSenha');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Associado $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuario', array());

        return parent::getUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuario($usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuario', array($usuario));

        return parent::setUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdAssociado()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdAssociado();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdAssociado', array());

        return parent::getIdAssociado();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoAssociado($noAssociado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoAssociado', array($noAssociado));

        return parent::setNoAssociado($noAssociado);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoAssociado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoAssociado', array());

        return parent::getNoAssociado();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuCpf($nuCpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuCpf', array($nuCpf));

        return parent::setNuCpf($nuCpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuCpf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuCpf', array());

        return parent::getNuCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuRg($nuRg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuRg', array($nuRg));

        return parent::setNuRg($nuRg);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuRg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuRg', array());

        return parent::getNuRg();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtNascimento($dtNascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtNascimento', array($dtNascimento));

        return parent::setDtNascimento($dtNascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtNascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtNascimento', array());

        return parent::getDtNascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsEndereco($dsEndereco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsEndereco', array($dsEndereco));

        return parent::setDsEndereco($dsEndereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsEndereco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsEndereco', array());

        return parent::getDsEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsCidade($dsCidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsCidade', array($dsCidade));

        return parent::setDsCidade($dsCidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsCidade', array());

        return parent::getDsCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsProfissao($dsProfissao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsProfissao', array($dsProfissao));

        return parent::setDsProfissao($dsProfissao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsProfissao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsProfissao', array());

        return parent::getDsProfissao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsEnderecoCom($dsEnderecoCom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsEnderecoCom', array($dsEnderecoCom));

        return parent::setDsEnderecoCom($dsEnderecoCom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsEnderecoCom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsEnderecoCom', array());

        return parent::getDsEnderecoCom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuTelefoneCom($nuTelefoneCom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuTelefoneCom', array($nuTelefoneCom));

        return parent::setNuTelefoneCom($nuTelefoneCom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuTelefoneCom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuTelefoneCom', array());

        return parent::getNuTelefoneCom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuTelefone($nuTelefone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuTelefone', array($nuTelefone));

        return parent::setNuTelefone($nuTelefone);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuTelefone', array());

        return parent::getNuTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsEmail($dsEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsEmail', array($dsEmail));

        return parent::setDsEmail($dsEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsEmail', array());

        return parent::getDsEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setStAutorizaEmail($stAutorizaEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAutorizaEmail', array($stAutorizaEmail));

        return parent::setStAutorizaEmail($stAutorizaEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getStAutorizaEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAutorizaEmail', array());

        return parent::getStAutorizaEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getNuTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuTitulo', array());

        return parent::getNuTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuTitulo($nuTitulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuTitulo', array($nuTitulo));

        return parent::setNuTitulo($nuTitulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtCadastro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtCadastro', array());

        return parent::getDtCadastro();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtCadastro($dtCadastro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtCadastro', array($dtCadastro));

        return parent::setDtCadastro($dtCadastro);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario($idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function onPrePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onPrePersist', array());

        return parent::onPrePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function getStAlteraSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAlteraSenha', array());

        return parent::getStAlteraSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function setStAlteraSenha($stAlteraSenha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAlteraSenha', array($stAlteraSenha));

        return parent::setStAlteraSenha($stAlteraSenha);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

}
