<?php echo $this->doctype(); ?>

<html lang="pt">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Orthosim'); ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath() . 'http://fonts.googleapis.com/icon?family=Material+Icons')
        ->prependStylesheet($this->basePath() . 'https://fonts.googleapis.com/css?family=Roboto')
        ->prependStylesheet($this->basePath() . '/css/materialize.min.css')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/materialize.min.js')
        ->prependFile($this->basePath() . '/js/jquery.mask.min.js')
        ->prependFile($this->basePath() . '/js/jquery.min.js')
        ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . 'https://code.jquery.com/jquery-2.1.1.min.js')
        ->prependFile($this->basePath() . 'https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js')
    ;
    ?>

</head>
    <body>
    <header>
    <?php echo $this->partial('orthosim/topo.phtml');?>
        <ul id="slid-out" class="sid-nav fixed">
            <?php echo $this->partial('orthosim/menu.phtml') ?>
        </ul>
    </header>
    <main>
        <div class="content">
            <div class="row">
                <?php echo $this->content;?>
            </div>
        </div>
    </main>
    <script>
        $(document).ready(function () {
           $(".button-collapse").sideNav();
        });
    </script>
    </body>
</html>
