<div class="painel">
    <form id="solicitarAcessoForm" method="POST" role="form">
        <div class="card">
            <div class="card-content">
                <span class="card-title"><b>Solicitar Acesso</b></span>
                <div class="row">
                    <div class="input-field col s6">
                        <input name="nome" id="nome" type="text"  required>
                        <label for="nome">Nome</label>
                    </div>
                    <div class="input-field col s6">
                        <select name="tpSexo">
                            <option value="" disabled selected>Selecione</option>
                            <option value="M">Masculino</option>
                            <option value="F">Feminino</option>
                            <option value="O">Outros</option>
                        </select>
                        <label for="sexo">Sexo</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6" >
                        <input name="email" id="email" type="text" required>
                        <label for="email">Email</label>
                    </div>
                    <div class="input-field col s6">
                        <input name="email_confirm" id="email_confirm" type="text" required autocomplete="off">
                        <label for="email_confirm">Confirme o Email</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <input name="fone_cel" id="fone_cel" type="text" required>
                        <label for="fone_cel">Telefone Celular</label>
                    </div>
                    <div class="input-field col s6">
                        <input name="fone_fixo" id="fone_fixo" type="text" >
                        <label for="fone_fixo">Telefone Fixo</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <input name="senha" id="senha" type="password" required>
                        <label for="senha">Senha</label>
                    </div>
                    <div class="input-field col s6">
                        <input name="confirm_senha" id="senha" type="password" required>
                        <label for="senha">Confirme sua senha</label>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12 right-align">
                        <button id="btn-cancelar" class="waves-effect waves-light btn red lighten-1" type="button">
                            Cancelar
                        </button>
                        <button id="btn-limpar" class="waves-effect waves-light btn grey lighten-1" type="reset">
                            Limpar
                        </button>
                        <button id="btn-cadastrar" class="waves-effect waves-light btn green" type="button" name="submit">
                            Cadastrar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div id="resultado"></div>
<script type="text/javascript">
    $(document).ready(function () {
        $('select').material_select();
        $('#btn-cancelar').click(function () {
            window.location = '/index/index';
        });
        $('#btn-cadastrar').click(function () {
            $.ajax({
                type: 'POST',
                data: $('#solicitarAcessoForm').serialize(),
                url: "/usuario/cadastrar",
                success: function (data) {
                    $('#resultado').html(data);

                }
            });
        });
    });

</script>